kernel:
    resource: ../src/Shared/Infrastructure/Kernel.php
    type: annotation

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

api_refresh_token:
    path: /api/auth/token/refresh

api_login_check:
    path: /api/auth/token/login
    methods: [ POST ]

users:
    resource: ../src/Users/Infrastructure/Controller/
    type: annotation

profiles:
    resource: ../src/Profiles/Infrastructure/Controller/
    type: annotation

friends:
    resource: ../src/Friends/Infrastructure/Controller/
    type: annotation

chats:
    resource: ../src/Chats/Infrastructure/Controller/
    type: annotation